config/routes.rb
Rails.application.routes.draw do

  resources :bookings, except: [:new, :edit, :show, :update, :update]
  resources :line_items, except: [:new, :edit, :index, :show, :update, :update]
  resources :carts, except: [:new,:edit,:index]
  resources :cinemas, except: [:show]
  resources :screenings, except: [:show]
  resources :movies, except: [:index]
  devise_for :users

  resources :carts do
    collection do
      post :create_booking
    end
  end

  root 'home#home'
  get 'home/book_tickets'
  get 'home/restable'
  get 'home/contact'

  get 'contact', to: 'home#contact'
  get 'allresources', to: 'home#restable'
  get 'booking', to: 'home#book_tickets'

  post 'request_contact', to: 'home#request_contact'
end

app/models/screening.rb
class Screening < ApplicationRecord
  ### Scopes:
  # Filters the screenings on whether they have already been screened
  scope :screening_passed, -> {
    where("screening_date < ?", Date.today)
  }
  # Filters the screenings that have not yet screened
  scope :screening_upcoming, -> {
    where("screening_date >= ?", Date.today)
  }

  ### Associations:
  # The screening can have many line items, and if it belongs to one it cannot be destroyed
  has_many :line_items, dependent: :restrict_with_error
  belongs_to :movie

  ### Validations:
  # Checks whether the fields are not null
  validates :movie, :price, :screening_date, :cinema, :screening_time, :arena, :available_seats, presence: true
  # Checks if price is a positive number
  validates :price, numericality: { greater_than: 0 }
  # Checks if available seats is a positive integer
  validates :available_seats, numericality: { only_integer: true, greater_than: 0}
  # Checks if the screening type is within the avaiable movie screening type
  validates :screening_type, inclusion: { in: %w(2D 3D 4D), message: "#{I18n.t('messages.validations.screening_type')}"}


  # A method used to search for specific screenings based on the date and cinema it plays in
  def self.search(search)
    # If parameters defined
    if search
      screenings = Screening.all
      # Filters the screenings based on the cinema played in
      screenings = screenings.where(cinema: search[:cinema])
      # Filters the filtered screenings based on the screening date passed in the parameter (search)
      screenings = screenings.where(screening_date: search[:screening_date])
      # Returns filtered screenings
      return screenings
    # If there are no parameters
    else
      return []
    end
  end
end

app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController
  # Users are not allowed to perform any actions except viewing show
  # Only admin can perform the other actions and visit other views
  before_action :is_admin, except: [:index]
  before_action :set_screening, only: [:edit, :update, :destroy]

  # GET /screenings
  # GET /screenings.json
  def index
    # Getting the date specified from the parameters
    date = screening_params[:screening_date].split('-')
    # Converting it from string to date to be used in the view
    @date = Date.new(date[0].to_i, date[1].to_i, date[2].to_i)

    # Uses a Screening method searching for screenings with
    # specific date and specific cinema, passed in through parameters.
    screenings = Screening.search(screening_params)

    # Using a hash map to map movies to screenings on that day and in that cinema
    @screenings = {}
    screenings.each do |screening|
      # If there is already a movie with the key then the screening is appended to already existing movie
      if @screenings.key?(screening.movie)
        @screenings[screening.movie].append(screening)
      # Else the movie is added as the key and an empty array is defined as the key
      else
        @screenings[screening.movie] = []
        # Add the screening as the value of the array corresponding to that movie
        @screenings[screening.movie].append(screening)
      end
    end

    # Iterating through all the movies in the hash
    @screenings.each do |movie, screening|
        # Sorting each screening array based on the screening_time
        screening = screening.sort_by {|s| s.screening_time}
        # Replacing the previous screening time with the sorted array of screenings for that movie
        @screenings[movie] = screening
    end
  end

  # If a parameters are missing (specifically in the index)
  # The program will take the user to the book tickets view
  rescue_from ActionController::ParameterMissing do |exception|
    redirect_to '/booking'
  end

  # GET /screenings/new
  def new
    @screening = Screening.new
  end

  # GET /screenings/1/edit
  def edit
  end

  # POST /screenings
  # POST /screenings.json
  def create
    @screening = Screening.new(screening_params)

    respond_to do |format|
      if @screening.save
        format.html { redirect_to allresources_url, notice: I18n.t('screenings.name') + I18n.t('messages.success') + I18n.t('messages.actions.create') }
        format.json { render :show, status: :created, location: allresources_url }
      else
        format.html { render :new }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screenings/1
  # PATCH/PUT /screenings/1.json
  def update
    respond_to do |format|
      if @screening.update(screening_params)
        format.html { redirect_to allresources_url, notice: I18n.t('screenings.name') + I18n.t('messages.success') + I18n.t('messages.actions.update')}
        format.json { render :show, status: :ok, location: allresources_url }
      else
        format.html { render :edit }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenings/1
  # DELETE /screenings/1.json
  def destroy
    respond_to do |format|
      if @screening.destroy
        format.html { redirect_to allresources_url, notice: I18n.t('screenings.name') + I18n.t('messages.success') + I18n.t('messages.actions.destroy')}
        format.js   { flash[:notice] = I18n.t('screenings.name') + I18n.t('messages.success') + I18n.t('messages.actions.destroy')}
      else
        format.html { redirect_to allresources_url, notice: I18n.t('screenings.name') + I18n.t('messages.fail_in_use')}

      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screening
      @screening = Screening.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def screening_params
      params.require(:screening).permit(:movie_id, :screening_type, :screening_date, :cinema, :price, :screening_time, :arena, :available_seats)
    end


end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/views/screenings/_form.html.haml
= form_for @screening, id: "screeningForm" do |f|
  - if @screening.errors.any?
    #error_explanation
      %h2= "#{pluralize(@screening.errors.count, "error")} #{t('prohibited_p1')} #{t('screenings.name_l')} #{t('prohibited_p2')}#{t('colon')}"
      %ul
        - @screening.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :movie
    = f.collection_select :movie_id, Movie.all, :id, :title
  .field
    = f.label :cinema
    = f.collection_select :cinema, Cinema.all, :name, :name
  .field
    = f.label :price
    = f.text_field :price, class: "positiveNumber"
  .field
    = f.label :screening_time
    = f.text_field :screening_time
  .field
    = f.label :screening_date
    = f.date_select :screening_date
  .field
    = f.label :arena
    = f.text_field :arena
  .field
    = f.label :available_seats
    = f.number_field :available_seats, class: "postiveNumber"
  .field
    = f.label :screening_type
    = f.text_field :screening_type, class: "isType"
  .actions
    = f.submit t('save_button')

app/views/screenings/destroy.js.erb
$('#screening_<%= @screening.id %>').hide();

app/views/screenings/edit.html.haml
%h1= "#{t('actions.edit')} #{t('screenings.name')}"

= render 'form'

= link_to t('back_button'), allresources_path

app/views/screenings/index.html.haml
%br
.container{:id => "screenings_container"}
  %h1{:id => "screenig_index_header"}= "#{t('.screenings_for', date: @date.strftime(t('date_format_2')))}"
  %hr
  -@screenings.each do |movie, screenings|
    %br
    .row
      .col-xs-4.col-sm-3
        %img{:class => "screening_index_images img-responsive", :src => "#{movie.poster}", :alt => "#{movie.title} #{t('movies.errors.image_missing')}"}
      .col-xs-7
        %h3= "#{movie.title}"
        %p
          %b= "#{t('movies.attributes.director')}#{t('colon')}"
          = movie.director
        %p
          %b
            = "#{t('movies.attributes.actors')}#{t('colon')}"
          = movie.actors
        %p
          %b
            = "#{t('movies.attributes.genres')}#{t('colon')}"
          = movie.genre
        %p
          %b
            = "#{t('movies.attributes.duration')}#{t('colon')}"
          = "#{t('minute', duration: movie.duration)}"
    %br
    %hr
    .row.justify-content-start
      -screenings.each do |screening|
        .col-xs-2
          - if user_signed_in?
            = button_to screening.screening_time.strftime("%H:%M"), line_items_path(line_item: {screening_id: screening}), data: { confirm: "#{t('.add_cart_confirm')}" }, class: "screening_button_times", remote: true
          - else
            = button_to screening.screening_time.strftime("%H:%M"), line_items_path(line_item: {screening_id: screening}), data: { confirm: "#{t('.add_cart_confirm')}" }, class: "screening_button_times"

          %p{:class => "text_screening_type"}
            %b= screening.screening_type
            = t('vertical_line')
            = t('pound', price: screening.price)
    %hr
    %br

app/views/screenings/new.html.haml
%h1= "#{t('actions.new')} #{t('screenings.name')}"

= render 'form'

= link_to t('back_button'), allresources_path