config/routes.rb
Rails.application.routes.draw do

  resources :bookings, except: [:new, :edit, :show, :update, :update]
  resources :line_items, except: [:new, :edit, :index, :show, :update, :update]
  resources :carts, except: [:new,:edit,:index]
  resources :cinemas, except: [:show]
  resources :screenings, except: [:show]
  resources :movies, except: [:index]
  devise_for :users

  resources :carts do
    collection do
      post :create_booking
    end
  end

  root 'home#home'
  get 'home/book_tickets'
  get 'home/restable'
  get 'home/contact'

  get 'contact', to: 'home#contact'
  get 'allresources', to: 'home#restable'
  get 'booking', to: 'home#book_tickets'

  post 'request_contact', to: 'home#request_contact'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :is_admin, only: [:restable]

  def home
    # Filters the movies into two arrays with the use of scopes
    # Firstly, the upcoming movies, i.e. all the movies that are released after today
    @upcoming_movies = Movie.release_after(Date.today)
    # Then, the released movies, i.e. all the movies that have been released before today
    @released_movies = Movie.release_before(Date.today)
  end

  def restable
    # Sorts all the movies by the date so that the table it easier to follow
    movies = Movie.all
    @movies = movies.sort_by {|movie| movie.release_date}

    @cinemas = Cinema.all

    # Filters all the screenings that have not happened yet
    screenings = Screening.screening_upcoming
    # Sorts the screenings based on screening date
    @screenings = screenings.sort_by{|screening| screening.screening_date}

    # Destroying screenings that have passed
    screenings_passed = Screening.screening_passed
    screenings_passed.destroy_all

    # Bookings filtered to show upcoming ones, not the history
    @bookings = Booking.booking_upcoming
  end


  def contact
  end


  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    # If there is no email, an error message will be displayed
    if email.blank?
      flash[:alert] = I18n.t('messages.request_contact.no_email')
      redirect_to contact_url
    # Or if there is no message supplied
    elsif message.blank?
      flash[:alert] = I18n.t('messages.request_contact.no_message')
      redirect_to contact_url
    # Otherwise the email will be sent
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('messages.request_contact.email_sent')
      redirect_to root_path
    end
  end


  def book_tickets
    @movies = Movie.all
    @screenings = Screening.all
    @cinemas = Cinema.all

    # Displays screenings for today and the upcoming week
    @dates_week = []
    today = Date.today
    i = 0
    loop do
      if i == 7
        break
      end
      @dates_week.append(today+i)
      i+=1
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/book_tickets.html.haml
#book_screenings
  %h2= "#{t('screenings.currently')} #{t('screenings.name')}"

  .container
    %h3= "#{t('.search')}#{t('colon')}"
    =form_tag(screenings_path, method:"get") do
      %select{:name => "screening[cinema]", :class => "form-control"}
        - @cinemas.each do |cinema|
          %option{:value => "#{cinema.name}"}= cinema.name

      %select{:name => "screening[screening_date]", :class => "form-control"}
        - @dates_week.each do |date|
          %option{:value => "#{date}"}= date

      =submit_tag(t('submit_button'))

app/views/home/contact.html.haml
.container-fluid
  .col-md-6.mx-auto
    = form_tag request_contact_path, method: 'post', :id => "contactForm" do
      .form-group.row
        %h1= t('.title')
        %br
      .row
        %p= t('.contact_us')
      .row
        = label_tag :name, "#{t('contact.name')}#{t('colon')}"
      .row
        = text_field_tag :name, '', title: "#{t('.enter')} #{t('contact.name')}", placeholder: "#{t('contact.name')}", size:40, class: "input_text_field"
      .row
        = label_tag :email, "#{t('contact.email')}#{t('colon')}"
      .row
        = email_field_tag :email, '', title: "#{t('.enter')} #{t('contact.email')}", placeholder: "#{t('contact.email')}", size:40, class: "input_text_field"
      .row
        = label_tag :telephone, "#{t('contact.telephone')}#{t('colon')}"
      .row
        = telephone_field_tag :telephone, '', title: "#{t('.enter')} #{t('contact.telephone')} #{t('.number')}", placeholder: "#{t('contact.telephone')}", size: 40, class: "input_text_field"
      .row
        = label_tag :message, t('.message')
      .row
        = text_area_tag :message, '', title: t('.enter_message'), id: "message_box_contact", placeholder: "#{t('.message')}"
      .row.body
        = submit_tag t('home.shared.header.contact'),:class => "btn btn-outline-secondary"

  .row
    .col.column-2
      .div-paragraph
        %br
        %br
        %h2= "#{t('.connect')}#{t('colon')}"
        %br
        %p= "#{t('.support')}#{t('colon')}"
        %p
        = "#{t('.email_us')}"
        = "#{t('.email_example')}"

      .div-paragraph
        %h4
          %b= "#{t('.town_country_1')}"
        %p= "#{t('.random_street_1')}"
        %p= "#{t('.town_1')}"
        %p= "#{t('.country')}"

      .div-paragraph
        %h4
          %b= "#{t('.town_country_1')}"
        %p= "#{t('.random_street_2')}"
        %p= "#{t('.town_1')}"
        %p= "#{t('.country')}"

app/views/home/home.html.haml
#main
  %br
  .container
    %h2= "#{t('screenings.currently')} #{t('in')} #{t('cinemas.name_p')}"
    %br
    %br
    .row
      - @released_movies.each do |movie|
        .col-sm-3
          %a{:href => "movies/#{movie.id}", class: "poster_link"}
            %img{:src => "#{movie.poster}", :alt => "#{movie.title} #{t('movies.errors.image_missing')}", :class => "poster_home img-responsive"}
          %h2
            %a{:href => "movies/#{movie.id}", :class => "title_links_upcoming"}= movie.title
        .col-sm-1
  %br

  .container
    %h2{id: "upcoming_mov"}= "#{t('bookings.index.upcoming')} #{t('movies.name_p')}"
    %br
    %br
    .row
      - @upcoming_movies.each do |movie|
        .col-sm-3
          %a{:href => "movies/#{movie.id}"}
            %img{:src => "#{movie.poster}", :alt => "#{movie.title} #{t('.movies.errors.image_missing')}", :class => "poster_home img-responsive"}
          %h2
            %a{:href => "movies/#{movie.id}", :class => "title_links_upcoming"}= movie.title
        .col-sm-1

  %br

app/views/home/restable.html.haml
#resources_div
  %h2= t('movies.name_p')
  %br
  %table{:id => "movie_res_table", :class => "table table-striped table-sm table-hover"}
    %thead
      %tr
        %th{:scope => "col"}= t('movies.attributes.poster')
        %th{:scope => "col"}= t('movies.attributes.title')
        %th{:scope => "col"}= t('movies.attributes.director')
        %th{:scope => "col"}= t('movies.attributes.genres')
        %th{:scope => "col"}= t('movies.attributes.duration')
        %th{:scope => "col"}= t('movies.attributes.country')
        %th{:scope => "col"}= t('movies.attributes.release_date')
        %th{:scope => "col"}= t('movies.attributes.actors')
        %th{:scope => "col"}= t('movies.attributes.restrictions')
        %th{:scope => "col", :id => "summary_column"}= t('movies.attributes.summary')
        %th{:scope => "col"}
    %tbody
      - @movies.each_with_index do |movie,i|
        %tr{:id => "movie_#{movie.id}"}
          %td{:scope => "row", :class => "movie_res_table_cell"}
            %a{:href => "movies/#{movie.id}"}
              %img{:src => "#{movie.poster}", :alt => "NaN", :class => "movie_poster_res_table "}
          %td{:scope => "row", :class => "movie_res_table_cell"}
            %a{:href => "movies/#{movie.id}", :class => "resource_table_links"}= movie.title
          %td{:scope => "row", :class => "movie_res_table_cell"}= movie.director
          %td{:scope => "row", :class => "movie_res_table_cell"}= movie.genre
          %td{:scope => "row", :class => "movie_res_table_cell"}= movie.duration
          %td{:scope => "row", :class => "movie_res_table_cell"}= movie.country
          %td{:scope => "row", :class => "movie_res_table_cell"}= movie.release_date
          %td{:scope => "row", :class => "movie_res_table_cell"}= movie.actors
          %td{:scope => "row", :class => "movie_res_table_cell"}= movie.restrictions
          %td{:scope => "row", :class => "movie_res_table_cell"}= movie.summary
          %td{:scope => "row", :class => "movie_res_table_cell", :id => "movie_res_table_cell_links"}
            = link_to t('edit_button'), edit_movie_path(movie)
            %br
            = link_to t('destroy_button'), movie, method: :delete, data: { confirm: t('destroy_confirm') }, remote: true

  %br

  = link_to "#{t('actions.new')} #{t('movies.name')}", new_movie_path

  %br
  %br

  %h2= t('screenings.name_p')

  %br

  %table{:class => "table table-striped table-sm table-hover"}
    %thead
      %tr
        %th{:scope => "col"}= t('movies.name')
        %th{:scope => "col"}= t('screenings.attributes.price')
        %th{:scope => "col"}= t('screening.attributes.screening_time')
        %th{:scope => "col"}= t('screening.attributes.screening_date')
        %th{:scope => "col"}= t('cinemas.name')
        %th{:scope => "col"}= t('screenings.attributes.arena')
        %th{:scope => "col"}= "#{t('screenings.attributes.available')} #{t('screenings.attributes.seats')}"
        %th{:scope => "col"}= "#{t('screenings.attributes.sold')} #{t('screenings.attributes.seats')}"
        %th{:scope => "col"}= t('screenings.attributes.type')
        %th{:scope => "col"}
        %th{:scope => "col"}
        %th{:scope => "col"}
    %tbody
      - @screenings.each do |screening|
        %tr{:id => "screening_#{screening.id}"}
          %td{:scope => "row"}= screening.movie.title
          %td{:scope => "row"}= screening.price
          %td{:scope => "row"}= screening.screening_time.strftime("%H:%M")
          %td{:scope => "row"}= screening.screening_date.strftime("%d/%m/%Y")
          %td{:scope => "row"}= screening.cinema
          %td{:scope => "row"}= screening.arena
          %td{:scope => "row"}= screening.available_seats
          %td{:scope => "row"}= screening.sold_seats
          %td{:scope => "row"}= screening.screening_type
          %td{:scope => "row"}= link_to t('show_button'), screening
          %td{:scope => "row"}= link_to t('edit_button'), edit_screening_path(screening)
          %td{:scope => "row"}= link_to t('destroy_button'), screening, method: :delete, data: { confirm: t('destroy_confirm') }, remote: true
  %br

  = link_to "#{t('actions.new')} #{t('screenings.name')}", new_screening_path

  %br
  %br

  %h2= t('cinemas.name_p')

  %table{:id => "cinema_res_table", :class => "table table-striped table-sm table-hover"}
    %thead
      %tr
        %th{:scope => "col"}= t('cinemas.attributes.name')
        %th{:scope => "col"}= t('cinemas.attributes.address')
        %th{:scope => "col"}= t('cinemas.attributes.image')
        %th{:scope => "col"}
        %th{:scope => "col"}
        %th{:scope => "col"}

    %tbody
      - @cinemas.each do |cinema|
        %tr{:id => "cinema_#{cinema.id}"}
          %td{:scope => "row"}= cinema.name
          %td{:scope => "row"}= cinema.address
          %td{:scope => "row"}= cinema.image
          %td{:scope => "row"}= link_to t('show_button'), cinema
          %td{:scope => "row"}= link_to t('edit_button'), edit_cinema_path(cinema)
          %td{:scope => "row"}= link_to t('destroy_button'), cinema, method: :delete, :data => { confirm: t('destroy_confirm')}, remote: true

  %br

  = link_to "#{t('actions.new')} #{t('cinemas.name')}", new_cinema_path

  %br
  %br

  %h2= t('bookings.name_p')

  %table{:id => "cinema_res_table", :class => "table table-striped table-sm table-hover"}
    %thead
      %tr
        %th{:scope => "col"}= t('bookings.attributes.user')
        %th{:scope => "col"}= t('movies.name')
        %th{:scope => "col"}= t('screenings.attributes.screening_time')
        %th{:scope => "col"}= t('screenings.attributes.screening_time')
        %th{:scope => "col"}= t('bookings.attributes.quantity')

    %tbody
      - @bookings.each do |booking|
        %tr
          %td{:scope => "row"}= User.find_by(id: booking.user_id).email
          %td{:scope => "row"}= booking.movie_title
          %td{:scope => "row"}= booking.booked_time
          %td{:scope => "row"}= booking.booked_date
          %td{:scope => "row"}= booking.quantity


  %br

  = link_to "#{t('actions.new')} #{t('bookings.name')}", new_cinema_path